### ISSUE TITLE
Error: Render frame was disposed before WebFrameMain could be accessed

### ISSUE THREAD

**Issue by greenozon** [opengs/uashield#223]
Got tons of errors like this over tonight
ver 1.0.6
Ubuntu Linux

```
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.097Z | HTTP | https://satom.ru | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.097Z | HTTP | http://admin.satom.ru/ | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.098Z | HTTP | http://admin.satom.ru/ | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.099Z | HTTP | http://admin.satom.ru/ | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.099Z | HTTP | http://admin.satom.ru/ | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.100Z | HTTP | https://service.egais.ru | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.100Z | HTTP | https://service.egais.ru | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.101Z | HTTP | https://egais.ru | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.101Z | HTTP | https://egais.ru | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
2022-05-04T04:49:53.102Z | HTTP | https://service.egais.ru | DOWN OR BLOCKED
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter._send (<anonymous>)
    at EventEmitter.n.send (node:electron/js2c/browser_init:165:417)
    at EventEmitter.b.send (node:electron/js2c/browser_init:161:2494)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:34:13638)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybjSg3tv/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
Killed

```

**Comment by opengs** [comment]
Hej, sorry for the long response. First time seeing this issue :) Looks like something not related to the UACyberSHIELD, but the library under the hood.

There are a lot of similar issues on the internet related to the electron in different applications. Like Skype (it uses the same tech) https://answers.microsoft.com/en-us/skype/forum/all/skype-fails-to-launch/e85fddd3-9579-435a-8d90-3c0a4dd354a8 , but I may not be appliable to this case.

At the moment, I can't reproduce the bug, so it's very hard to find the problem and fix it :( . It may be only related to your PC, or maybe some very rare conditions :( . Maybe you have more info that will help to identify an issue, like after what actions it started to do this? If not, we have to wait for more reports from other users :(

**Comment by greenozon** [comment]
Looks like bug in Electron engine...
eg: https://github.com/electron-userland/electron-builder/issues/6760
