### ISSUE TITLE
TypeError: Object has been destroyed

### ISSUE THREAD

**Issue by greenozon** [opengs/uashield#228]
I"m getting these errors very often when closing the app
ver 1.0.6
Ubuntu Linux

```
2022-06-30T05:02:39.033Z | HTTP | https://vebeng.ru/ | 409
2022-06-30T05:02:39.056Z | HTTP | https://www.novatek.ru/en/search/index.php?source_id_4=1&sortby_4=&q_4=ru&search_page_4=1001&te_object_id_4=&items_per_page_4=10&date_from_4=&date_to_4= | 404
2022-06-30T05:02:39.058Z | HTTP | https://faspo.arbitr.ru/ | 403
2022-06-30T05:02:39.096Z | HTTP | https://forbusiness.roscongress.org/ | DOWN OR BLOCKED
TypeError: Object has been destroyed
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybBevnbC/resources/app.asar/electron-main.js:34:12631)
    at EventEmitter.emit (node:events:390:28)
    at Ot.emit (/tmp/.mount_UA-CybBevnbC/resources/app.asar/electron-main.js:1:45367)
    at EventEmitter.<anonymous> (/tmp/.mount_UA-CybBevnbC/resources/app.asar/electron-main.js:1:45684)
    at EventEmitter.emit (node:events:390:28)
    at St.<anonymous> (/tmp/.mount_UA-CybBevnbC/resources/app.asar/electron-main.js:1:45040)
    at Generator.next (<anonymous>)
    at i (/tmp/.mount_UA-CybBevnbC/resources/app.asar/electron-main.js:1:44067)
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:61:5)
2022-06-30T05:02:39.105Z | HTTP | https://vebeng.ru/ | 409
```

**Comment by opengs** [comment]
This is a race condition while closing the window. The DDoS engine sends a message about new attack -> at the same time someone closes the window -> the program tries to send a message to the closed window. Its safe :) So let it be the lowest priority, I don't know how to fix this at the moment.
