### ISSUE TITLE
not enough file handles - build 1.0.11

### ISSUE THREAD

**Issue by greenozon** [opengs/uashield#237]
running couple of days, htting this error  (lots of such an errors):
Ubuntu OS
```
pageview
null
Error: EMFILE: too many open files, open '/home/user/.config/UA Cyber SHIELD/config.json'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at Object.readFileSync (node:fs:453:35)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at ElectronStore.get store [as store] (/tmp/.mount_UA-Cybb4Pw16/resources/app.asar/node_modules/conf/dist/source/index.js:276:29)
    at ElectronStore.set (/tmp/.mount_UA-Cybb4Pw16/resources/app.asar/node_modules/conf/dist/source/index.js:170:17)
    at IpcMainImpl.<anonymous> (/tmp/.mount_UA-Cybb4Pw16/resources/app.asar/electron-main.js:34:13253)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10120)
    at EventEmitter.emit (node:events:390:28) {
  errno: -24,
  syscall: 'open',
  code: 'EMFILE',
  path: '/home/user/.config/UA Cyber SHIELD/config.json'
}
pageview
null
Loaded proxy list
Failed to load targets from https://bitbucket.org/uncork-vacant-shallow/exposable-ibuprofen/raw/6a078f9eee1eca67ca1d274983e256d244888820/40.json. Error: Error: Failed to load received data as JSON. Error: SyntaxError: Unexpected token 
                     in JSON at position 0
Loaded targets list
superagent: double callback bug
Error: EMFILE: too many open files, open '/home/user/.config/UA Cyber SHIELD/config.json'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at Object.readFileSync (node:fs:453:35)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at ElectronStore.get store [as store] (/tmp/.mount_UA-Cybb4Pw16/resources/app.asar/node_modules/conf/dist/source/index.js:276:29)
    at ElectronStore.set (/tmp/.mount_UA-Cybb4Pw16/resources/app.asar/node_modules/conf/dist/source/index.js:170:17)
    at IpcMainImpl.<anonymous> (/tmp/.mount_UA-Cybb4Pw16/resources/app.asar/electron-main.js:34:13253)
    at IpcMainImpl.emit (node:events:390:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10120)
    at EventEmitter.emit (node:events:390:28) {
  errno: -24,
  syscall: 'open',
  code: 'EMFILE',
  path: '/home/user/.config/UA Cyber SHIELD/config.json'
}
pageview
Error: getaddrinfo EBUSY www.google-analytics.com

............................
```

**Comment by BogdanDevUA** [comment]
Try updating Node.js to the latest or earlier version
P.S. I don't know if it will help, but I advise you to try
